networks:
  trackorinet:

services:
  php:
    container_name: trackori-php
    build: .
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - trackorinet

  db:
    container_name: trackori-db
    image: mariadb:latest
    restart: always
    env_file:
        - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
        - trackorinet 

  phpmyadmin:
    container_name: trackori-admin
    image: phpmyadmin:5.2.2-apache
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    depends_on:
      - db
    ports:
      - "8081:80"
    networks:
        - trackorinet 

volumes:
  db-data:
